import { StyleSheet } from "react-native";

export default StyleSheet.create({
  // Welcome
  welcome: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  welcomeImage: {
    width: "70%",
    height: 250,
    maxWidth: 280,
    marginBottom: 20,
  },
  welcomeFooter: {
    position: "absolute",
    bottom: 8,
    fontSize: 14,
    color: "#6b7280",
  },

  loadingRoot: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  loadingLogo: {
    width: "60%",
    maxWidth: 240,
    height: 180,
    marginBottom: 28,
  },
  loadingSkeletonContainer: {
    width: "100%",
    maxWidth: 360,
    marginBottom: 24,
  },
  loadingSkeletonBlock: {
    width: "100%",
    height: 18,
    borderRadius: 999,
    backgroundColor: "#e2e8f0",
    marginBottom: 14,
  },
  loadingSkeletonWide: {
    width: "100%",
  },
  loadingSkeletonSmall: {
    width: "65%",
  },
  loadingText: {
    fontSize: 16,
    color: "#475569",
    fontWeight: "600",
  },

  // Auth
  authScreen: {
    flex: 1,
    backgroundColor: "#fff",
  },
  authScroll: {
    flex: 1,
  },
  authContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 32,
    backgroundColor: "#fff",
    justifyContent: "center",
  },
  authLogo: {
    width: 160,
    height: 160,
    alignSelf: "center",
    marginBottom: 24,
  },
  authTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 16,
    color: "#475569",
    marginBottom: 28,
  },
  authInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 16,
    backgroundColor: "#f8fafc",
    fontSize: 16,
    color: "#0f172a",
  },
  authRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  authInputHalf: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#f8fafc",
    fontSize: 16,
    color: "#0f172a",
  },
  authInputHalfMargin: {
    marginRight: 12,
  },
  authSmallButton: {
    flex: 1,
    backgroundColor: "#047857",
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    height: 48,
  },
  authButton: {
    backgroundColor: "#047857",
    paddingVertical: 16,
    borderRadius: 24,
    alignItems: "center",
    marginBottom: 24,
  },
  authButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  authFooterText: {
    fontSize: 14,
    color: "#475569",
    textAlign: "center",
    marginTop: 20,
  },
  authLinkText: {
    color: "#047857",
    fontWeight: "600",
  },

  // Dashboard
  dashboardRoot: {
    flex: 1,
    backgroundColor: "#064e3b",
  },
  dashboardHeader: {
    paddingTop: 16,
    paddingHorizontal: 20,
    paddingBottom: 16,
    alignItems: "flex-start",
  },
  dashboardHeaderInner: {
    marginTop: 8,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  dashboardLogo: {
    width: 120,
    height: 52,
    marginBottom: 4,
  },
  dashboardTitle: {
    marginLeft: 4,
    fontSize: 28,
    fontWeight: "700",
    color: "#fff",
  },
  dashboardBody: {
    backgroundColor: "#f1f5f9",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingBottom: 112,
  },
  dashboardBannerGroup: {
    marginBottom: 24,
  },
  dashboardBannerItem: {
    marginRight: 12,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  dashboardBannerImage: {
    width: "100%",
    height: 144,
  },
  dashboardBannerTag: {
    position: "absolute",
    bottom: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dashboardBannerText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#0f172a",
  },
  dashboardCard: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 24,
    backgroundColor: "#fff",
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  dashboardCardIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  dashboardCardIconEmerald: {
    backgroundColor: "#d1fae5",
  },
  dashboardCardIconOrange: {
    backgroundColor: "#ffedd5",
  },
  dashboardCardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#0f172a",
  },
  dashboardCardSubtitle: {
    fontSize: 14,
    color: "#64748b",
  },
  dashboardMapCard: {
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  dashboardMapImage: {
    width: "100%",
    height: 176,
  },
  dashboardTabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  dashboardTabItem: {
    alignItems: "center",
  },
  dashboardTabText: {
    marginTop: 4,
    fontSize: 10,
    color: "#475569",
  },
  dashboardTabTextActive: {
    marginTop: 4,
    fontSize: 10,
    color: "#047857",
    fontWeight: "700",
  },
  dashboardScrollRoot: {
    flex: 1,
  },

  // Book
  bookScreen: {
    flex: 1,
    backgroundColor: "#f1f5f9",
  },
  bookHeader: {
    backgroundColor: "#064e3b",
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 28,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  bookHeaderTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
  },
  bookHeaderSubtitle: {
    marginTop: 8,
    color: "#d1fae5",
    fontSize: 14,
    lineHeight: 20,
  },
  bookContent: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  bookCard: {
    borderRadius: 28,
    backgroundColor: "#fff",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  bookRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  bookStatusBadge: {
    borderRadius: 24,
    backgroundColor: "#ecfdf5",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  bookStatusText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#166534",
  },
  bookSectionLabel: {
    fontSize: 14,
    color: "#475569",
    marginBottom: 8,
  },
  bookInputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  bookInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#f8fafc",
  },
  bookInputGap: {
    marginLeft: 12,
  },
  bookTripRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  bookTripOption: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: "center",
  },
  bookTripOptionActive: {
    borderColor: "#047857",
    backgroundColor: "#ecfdf5",
  },
  bookTripOptionInactive: {
    borderColor: "#e2e8f0",
    backgroundColor: "#fff",
  },
  bookTripOptionTextActive: {
    fontWeight: "600",
    color: "#166534",
  },
  bookTripOptionTextInactive: {
    fontWeight: "600",
    color: "#334155",
  },
  bookAddLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  bookAddLocationIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#e2e8f0",
    marginRight: 12,
  },
  bookAddLocationText: {
    color: "#047857",
    fontWeight: "600",
  },
  bookTextarea: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#f8fafc",
    marginBottom: 20,
    textAlignVertical: "top",
  },
  bookSubmitButton: {
    backgroundColor: "#047857",
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: "center",
  },
  bookSubmitText: {
    color: "#fff",
    fontWeight: "600",
  },

  // Chat
  chatScreen: {
    flex: 1,
    backgroundColor: "#f1f5f9",
  },
  chatHeader: {
    backgroundColor: "#064e3b",
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  chatHeaderText: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
  },
  chatBackRow: {
    paddingHorizontal: 20,
    paddingTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  chatThreadList: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  chatHeading: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 16,
  },
  chatThreadCard: {
    marginBottom: 16,
    borderRadius: 24,
    backgroundColor: "#fff",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  chatThreadHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  chatThreadName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0f172a",
  },
  chatThreadTime: {
    fontSize: 12,
    color: "#94a3b8",
  },
  chatThreadText: {
    fontSize: 14,
    color: "#64748b",
  },
  chatMessages: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  chatBubble: {
    marginBottom: 12,
    maxWidth: "80%",
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  chatBubbleSent: {
    alignSelf: "flex-end",
    backgroundColor: "#047857",
  },
  chatBubbleReceived: {
    alignSelf: "flex-start",
    backgroundColor: "#fff",
  },
  chatBubbleSentText: {
    color: "#fff",
  },
  chatBubbleReceivedText: {
    color: "#0f172a",
  },
  chatInputWrapper: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  chatInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  chatInput: {
    flex: 1,
    color: "#0f172a",
    fontSize: 16,
  },
  chatSendButton: {
    backgroundColor: "#047857",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  chatSendText: {
    color: "#fff",
    fontWeight: "600",
  },

  // Notification
  notificationScreen: {
    flex: 1,
    backgroundColor: "#f1f5f9",
  },
  notificationHeader: {
    backgroundColor: "#064e3b",
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  notificationHeaderTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
  },
  notificationTopRow: {
    paddingHorizontal: 20,
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  notificationSectionTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "600",
  },
  notificationButton: {
    borderRadius: 999,
    backgroundColor: "#fee2e2",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  notificationButtonText: {
    color: "#be123c",
    fontWeight: "600",
    fontSize: 12,
  },
  notificationList: {
    paddingHorizontal: 20,
    marginTop: 16,
  },
  notificationCard: {
    marginBottom: 16,
    borderRadius: 24,
    backgroundColor: "#fff",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  notificationCardRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  notificationAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#d1fae5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  notificationAvatarText: {
    color: "#166534",
    fontWeight: "700",
  },
  notificationCardContent: {
    flex: 1,
  },
  notificationCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  notificationTitle: {
    fontWeight: "600",
    color: "#0f172a",
  },
  notificationStatus: {
    fontSize: 12,
    color: "#166534",
    fontWeight: "600",
  },
  notificationDescription: {
    color: "#64748b",
    fontSize: 14,
    marginTop: 4,
  },
  notificationTime: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 12,
  },

  // Profile
  profileScreen: {
    flex: 1,
    backgroundColor: "#f1f5f9",
  },
  profileHeader: {
    backgroundColor: "#064e3b",
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  profileHeaderTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
  },
  profileContent: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  profileCard: {
    borderRadius: 28,
    backgroundColor: "#fff",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    alignItems: "center",
  },
  profileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    marginBottom: 16,
  },
  profileName: {
    color: "#0f172a",
    fontSize: 20,
    fontWeight: "700",
  },
  profileEmail: {
    color: "#64748b",
    fontSize: 14,
    marginBottom: 12,
  },
  profileEditButton: {
    marginTop: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#047857",
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  profileEditButtonText: {
    color: "#047857",
    fontWeight: "600",
  },
  profileMenu: {
    marginTop: 24,
  },
  profileMenuItem: {
    borderRadius: 24,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  profileMenuText: {
    color: "#0f172a",
    fontWeight: "500",
  },
  profileMenuTrailing: {
    color: "#64748b",
    fontSize: 14,
  },
  profileMenuTrailingRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileCalendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 12,
  },
  profileDateCell: {
    width: "48%",
    borderRadius: 18,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  profileDateCellSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#047857",
  },
  profileDateCellText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "600",
  },
  profileDateCloseButton: {
    marginTop: 16,
    borderRadius: 24,
    backgroundColor: "#047857",
    paddingVertical: 14,
    alignItems: "center",
  },
  profileDateCloseText: {
    color: "#fff",
    fontWeight: "700",
  },
  profileLogoutButton: {
    marginTop: 24,
    borderRadius: 24,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    alignItems: "center",
  },
  profileLogoutText: {
    color: "#dc2626",
    fontWeight: "600",
  },
  profileModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  profileModal: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  profileModalHeaderText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 16,
  },
  profileModalInput: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    backgroundColor: "#f8fafc",
    fontSize: 16,
    color: "#0f172a",
  },
  profileModalButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  profileModalButton: {
    flex: 1,
    backgroundColor: "#047857",
    borderRadius: 16,
    paddingVertical: 14,
    marginLeft: 8,
    alignItems: "center",
  },
  profileModalCancelButton: {
    backgroundColor: "#e5e7eb",
    marginLeft: 0,
    marginRight: 8,
  },
  profileModalButtonText: {
    color: "#fff",
    fontWeight: "700",
  },  
});
